project_id = "thldkqfacwfievhziepc"

[functions.notify-vendor-new-order]
verify_jwt = false

[functions.notify-order-status]
verify_jwt = false

[functions.generate-user-recommendations]
verify_jwt = false

[functions.onesignal-dispatcher]
verify_jwt = false


[functions.onesignal-broadcast]
enabled = true
verify_jwt = false
import_map = "./functions/onesignal-broadcast/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/onesignal-broadcast/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/onesignal-broadcast/*.html" ]
